from . import Graph, VertexPropertyMap

def sfdp_layout(*args, **kwargs) -> VertexPropertyMap: ...
def random_layout(*args, **kwargs) -> VertexPropertyMap: ...
def graph_draw(graph: Graph, **kwargs) -> VertexPropertyMap: ...
